stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: deltaprojects/kafka-manager:${CICD_GIT_TAG}
    env:
      PLUGIN_MTU: 1450
  when:
    event:
      include:
      - tag
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    event:
      include:
      - tag
timeout: 60
notification: {}
